# Generated by Django 4.1.5 on 2023-02-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DishRating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='dishCal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishes',
            name='dishRate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishes',
            name='dishType',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
