# Generated by Django 4.1.5 on 2023-02-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DishRating', '0004_alter_dishes_dishtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='dishDescribe',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
    ]
